spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: rtsd0220
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework:
        web: TRACE