spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: rtsd0220
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    org:
      springframework:
        web: TRACE